### PR TITLE
Update c2-intervals.md

### PR DESCRIPTION
**Pull request by John8245**

### CODE REVIEW

**Comment by evanwill** [comment]
@John8245 I am going to merge this PR for @smbutterfield to bring your class notes into the main website. 
You have been invited to join this repository, so once you accept the invite, you will be able to edit directly, so shouldn't work on your fork version going forward.

**Comment by evanwill** [comment]
@John8245 you should be able to accept the invite at this page: https://github.com/intmus/inttheory20-21/invitations

**Comment by John8245** [comment]
It says the invite is no longer available.

**Comment by evanwill** [comment]
@John8245 ummmm.... I just added you again and it looks like somehow you have accepted already. Not sure what was going on, but you should be a member now and able to edit this repo directly. Let me know!

**Pull request merged**
